version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    restart: always

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - app
